import test from 'node:test';
import assert from 'node:assert/strict';
import type { Answers, AssessmentConfig, Attempt, QuestionBank } from '../src/assessment/model.ts';
import { selectQuestions, scoreQuestions, isCorrect, improvementPoints } from '../src/assessment/core.ts';
import { ProgressStore, progressKey, type ProgressStorage } from '../src/assessment/progress.ts';
import { validateQuestionBank } from '../src/assessment/validate.ts';
import { fixtureChapter, fixtureCatalog } from './fixtures/chapter.ts';
import { assessmentFixtureBank } from './fixtures/assessment.ts';
const bank = assessmentFixtureBank;
const config: AssessmentConfig = { chapterId: fixtureChapter.id, objectives: fixtureChapter.objectives, bank };
const fixed = () => .42;
const select = (mode: 'before' | 'after', options = {}) => selectQuestions(bank, config.objectives, mode, { random: fixed, ...options });
const answersFor = (ids: readonly string[]): Answers => Object.fromEntries(ids.map(id => [id, bank.questions.find(q => q.id === id)!.correctChoiceIds]));
function attempt(id: string, questions = select('before'), answers = answersFor(questions.map(q => q.id))): Attempt {
  return { ...scoreQuestions(questions, answers, config.objectives), id, answers, questionIds: questions.map(q => q.id), completedAt: '2026-10-07T01:00:00.000Z' };
}
class Memory implements ProgressStorage {
  values = new Map<string,string>();
  getItem(key: string) { return this.values.get(key) ?? null; }
  setItem(key: string, value: string) { this.values.set(key,value); }
  removeItem(key: string) { this.values.delete(key); }
}
test('synthetic bank exercises all eight types with three objectives', () => { validateQuestionBank(bank, fixtureChapter, fixtureCatalog); assert.equal(new Set(bank.questions.map(q=>q.type)).size,8); });
test('selection distributes nine questions evenly with no duplicates', () => { const qs=select('before'); assert.equal(new Set(qs.map(q=>q.id)).size,9); for(const o of config.objectives) assert.equal(qs.filter(q=>q.objectiveId===o.id).length,3); });
test('Post covers the same objectives and avoids corresponding Pre IDs', () => { const pre=select('before'); const post=select('after',{avoidIds:pre.map(q=>q.id)}); assert.equal(post.length,12); assert(post.every(q=>!pre.some(p=>p.id===q.id))); for(const o of config.objectives) assert.equal(post.filter(q=>q.objectiveId===o.id).length,4); });
test('retry uses unused questions when capacity permits', () => { const first=select('after'); const next=select('after',{recentIds:first.map(q=>q.id)}); assert(next.every(q=>!first.some(p=>p.id===q.id))); });
test('sparse pools redistribute while covering available objectives', () => { const small:QuestionBank={...bank,beforeCount:8,questions:bank.questions.filter(q=>q.objectiveId===config.objectives[2].id||q.id==='fixture-question-1'||q.id==='fixture-question-2')}; const qs=selectQuestions(small,config.objectives,'before',{random:fixed}); assert.equal(qs.length,8); assert.equal(new Set(qs.map(q=>q.objectiveId)).size,3); });
test('selection never duplicates when a caller bypasses validation', () => { const qs=selectQuestions({...bank,afterCount:100},config.objectives,'after'); assert.equal(qs.length,bank.questions.length); assert.equal(new Set(qs.map(q=>q.id)).size,bank.questions.length); });
test('authoring validation rejects configured counts larger than eligible unique supply',()=>{assert.throws(()=>validateQuestionBank({...bank,afterCount:bank.questions.filter(q=>q.eligibility.includes('after')).length+1},fixtureChapter,fixtureCatalog),/question supply/);});
test('least recent IDs preferred when all candidates have been used', () => { const recent=bank.questions.map(q=>q.id); const qs=select('before',{recentIds:recent}); assert(qs.every(q=>recent.indexOf(q.id)<9)); });
test('all single-answer variants score deterministic one or zero', () => { for(const q of bank.questions.filter(q=>q.type!=='multiple-choice')) {assert(isCorrect(q,q.correctChoiceIds));assert(!isCorrect(q,[]));assert(!isCorrect(q,[q.choices.find(c=>!q.correctChoiceIds.includes(c.id))!.id]));} });
test('multiple choice requires exact set, no partial/extra/negative credit', () => { const q=bank.questions.find(q=>q.type==='multiple-choice')!;assert(isCorrect(q,[...q.correctChoiceIds].reverse()));assert(!isCorrect(q,[q.correctChoiceIds[0]]));assert(!isCorrect(q,q.choices.map(c=>c.id)));assert(!isCorrect(q,[])); });
test('objective breakdown sums correctly and includes unassessed objectives', () => { const q=bank.questions[0]; const s=scoreQuestions([q],{[q.id]:q.correctChoiceIds},config.objectives);assert.equal(s.correct,1);assert.equal(s.total,1);assert.equal(s.objectives.filter(o=>o.total===0).length,2); });
test('improvement uses percentage points, including decreases', () => {const before={correct:6,total:10,percentage:60,objectives:[]};const after={correct:12,total:14,percentage:86,objectives:[]};assert.equal(improvementPoints(before,after),26);assert.equal(improvementPoints(after,before),-26);});
test('first/latest Pre persist and only Post summaries are bounded', () => {const mem=new Memory();const store=new ProgressStore(config,mem);store.complete('before',attempt('first'));store.complete('before',attempt('second'));for(let i=0;i<15;i++)store.complete('after',{...attempt('post-'+i,select('after')),preAttemptId:'second'});const loaded=new ProgressStore(config,mem);assert.equal(loaded.data.pre.first?.id,'first');assert.equal(loaded.data.pre.latest?.id,'second');assert.equal(loaded.data.post.attempts.length,12);assert.equal(loaded.data.post.latest?.id,'post-14');});
test('best and latest Post are distinct and old best survives history cap', () => {const store=new ProgressStore(config,new Memory());const good=attempt('best',select('after'));store.complete('after',good);const wrong=Object.fromEntries(good.questionIds.map(id=>[id,[bank.questions.find(q=>q.id===id)!.choices.find(c=>!bank.questions.find(q=>q.id===id)!.correctChoiceIds.includes(c.id))!.id]]));for(let i=0;i<13;i++)store.complete('after',attempt('wrong-'+i,select('after'),wrong));assert.equal(store.data.post.best?.id,'best');assert.equal(store.data.post.latest?.correct,0);});
test('reset deletes only this Chapter key and preserves unrelated keys',()=>{const mem=new Memory();mem.setItem('other-app','keep');mem.setItem(progressKey('other-chapter'),'keep');const store=new ProgressStore(config,mem);store.complete('before',attempt('pre'));assert(store.reset());assert.equal(mem.getItem(progressKey(config.chapterId)),null);assert.equal(mem.getItem('other-app'),'keep');assert.equal(mem.getItem(progressKey('other-chapter')),'keep');});
test('corrupt JSON recovers only relevant key without throwing',()=>{const mem=new Memory();mem.setItem(progressKey(config.chapterId),'{broken');mem.setItem('other','keep');const store=new ProgressStore(config,mem);assert.equal(store.data.pre.latest,undefined);assert(store.notice.includes('reset'));assert.equal(mem.getItem('other'),'keep');});
test('corrupt scores cannot masquerade as valid saved results',()=>{const mem=new Memory();const s=new ProgressStore(config,mem);s.complete('before',attempt('pre'));const raw=JSON.parse(mem.getItem(progressKey(config.chapterId))!);raw.pre.latest.correct=999;mem.setItem(progressKey(config.chapterId),JSON.stringify(raw));assert.equal(new ProgressStore(config,mem).data.pre.latest,undefined);});
test('unknown schema remains untouched until deliberate reset',()=>{const mem=new Memory();const raw=JSON.stringify({schemaVersion:9});mem.setItem(progressKey(config.chapterId),raw);const store=new ProgressStore(config,mem);store.complete('before',attempt('pre'));assert.equal(mem.getItem(progressKey(config.chapterId)),raw);assert(store.reset());assert.equal(mem.getItem(progressKey(config.chapterId)),null);});
test('bank revision resets only the stale Chapter progress',()=>{const mem=new Memory();const old=new ProgressStore(config,mem);old.complete('before',attempt('pre'));const fresh=new ProgressStore({...config,bank:{...bank,version:2}},mem);assert.equal(fresh.data.pre.latest,undefined);assert(fresh.notice.includes('bank changed'));});
test('denied storage remains usable in memory and reports reset failure',()=>{const denied={getItem(){throw Error('denied')},setItem(){throw Error('denied')},removeItem(){throw Error('denied')}};const store=new ProgressStore(config,denied);store.complete('before',attempt('pre'));assert.equal(store.data.pre.latest?.id,'pre');assert(!store.reset());});
test('quota failure does not lose in-page scores',()=>{const mem=new Memory();mem.setItem=()=>{throw Error('quota')};const store=new ProgressStore(config,mem);store.complete('before',attempt('pre'));assert.equal(store.data.pre.latest?.id,'pre');assert(store.notice.includes('could not be saved'));});
test('malformed references and answer definitions fail authoring validation',()=>{assert.throws(()=>validateQuestionBank({...bank,questions:[{...bank.questions[0],objectiveId:'absent'}]},fixtureChapter,fixtureCatalog));assert.throws(()=>validateQuestionBank({...bank,questions:[{...bank.questions[0],correctChoiceIds:['absent']}]},fixtureChapter,fixtureCatalog));assert.throws(()=>validateQuestionBank({...bank,questions:[{...bank.questions[0],reviewAnchor:'absent'}]},fixtureChapter,fixtureCatalog));});
