import type { Question, QuestionBank, QuestionType } from '../../assessment/model';
import type { ReadingBlock } from '../../learning/model';
const chapterId = 'ethernet-port-operations';
function question(objectiveId: string, suffix: string, type: QuestionType, prompt: string, labels: string[], correct: number[], explanation: string, reviewAnchor: string, context?: readonly ReadingBlock[]): Question {
  const choices = labels.map((label, index) => ({ id: type === 'true-false' ? index === 0 ? 'true' : 'false' : `choice-${index + 1}`, label }));
  return { id: `ports-${suffix}`, chapterId, objectiveId, eligibility: ['before', 'after'], type, prompt, choices, correctChoiceIds: correct.map(index => choices[index].id), explanation, reviewAnchor, context };
}
const output = (text: string): ReadingBlock[] => [{ kind: 'cli', id: 'question-evidence', caption: 'Illustrative evidence for this question', lines: [{ kind: 'output', text }] }];
const intent = (suffix: string, type: QuestionType, prompt: string, labels: string[], correct: number[], explanation: string, context?: readonly ReadingBlock[]) => question('interface-intent', suffix, type, prompt, labels, correct, explanation, 'make-a-port-change', context);
const agreement = (suffix: string, type: QuestionType, prompt: string, labels: string[], correct: number[], explanation: string, context?: readonly ReadingBlock[]) => question('link-agreement', suffix, type, prompt, labels, correct, explanation, 'agree-on-a-link', context);
const evidence = (suffix: string, type: QuestionType, prompt: string, labels: string[], correct: number[], explanation: string, context?: readonly ReadingBlock[]) => question('interface-evidence', suffix, type, prompt, labels, correct, explanation, 'read-the-port', context);
const diagnosis = (suffix: string, type: QuestionType, prompt: string, labels: string[], correct: number[], explanation: string, context?: readonly ReadingBlock[]) => question('link-diagnosis', suffix, type, prompt, labels, correct, explanation, 'measure-link-health', context);
const distractorGuidance: Record<string, readonly { choiceId: string; text: string }[]> = {
  'ports-shared-capability': [{ choiceId: 'choice-1', text: 'The switch supports Gigabit, but the endpoint in this question does not. Negotiation must use a capability shared by both.' }],
  'ports-crc-delta': [{ choiceId: 'choice-2', text: '17 is the starting cumulative count, not the number added during the window.' }, { choiceId: 'choice-3', text: '19 is the ending cumulative count. Subtract the starting count to isolate the new errors.' }],
  'ports-range-verification': [{ choiceId: 'choice-3', text: 'Each range member has a separate physical path and peer. A shared edit does not prove shared link health.' }],
};
export const portQuestionBank: QuestionBank = {
  chapterId, version: 1, beforeCount: 8, afterCount: 12,
  questions: [
    intent('scope-repair', 'configuration-selection', 'Only Gi1/0/8 is authorized for restoration. Gi1/0/7 is healthy and Gi1/0/9 must stay disabled. Which change has the correct scope?', ['Select Gi1/0/8 and issue no shutdown.', 'Select the range Gi1/0/7 - 9 and issue no shutdown.', 'Issue no shutdown in global configuration without selecting an interface.', 'Reset all three interface configurations.'], [0], 'Selecting the individual authorized interface changes its administrative state without enabling the retired spare or editing the healthy port.'),
    intent('range-expansion', 'single-choice', 'You enter a description under interface range Gi1/0/11 - 12. How should you verify where the label was applied?', ['Search only for a saved interface-range object.', 'Inspect the individual running configurations of Gi1/0/11 and Gi1/0/12.', 'Check whether every port on the switch has the label.', 'Read startup configuration before checking the current running configuration.'], [1], 'Range mode applies the subcommand to each selected interface. Verify the live per-interface records; the range selection is not a persistent configuration object.'),
    intent('label-role', 'true-false', 'Changing an interface description from “old bench” to “recorder” changes the link’s negotiated speed.', ['True', 'False'], [1], 'Description is administrative documentation. It does not choose a physical operating speed or duplex.'),
    intent('undo-label', 'configuration-selection', 'A temporary description should be removed while speed, duplex and shutdown state stay intact. Which interface command fits?', ['no shutdown', 'no speed', 'no description', 'default interface GigabitEthernet1/0/7'], [2], 'no description removes the label only. The other commands change administrative/physical settings or reset a much wider interface configuration.'),
    intent('permission-scope', 'multiple-choice', 'After no shutdown is accepted, which facts still require independent verification? Select all that apply.', ['The peer is powered and permitted to operate.', 'A suitable physical path is present.', 'The two ends have a compatible operating mode.', 'The command has automatically repaired every damaged frame.'], [0,1,2], 'Administrative permission does not establish the peer, cable or compatible operating mode. It cannot repair damaged traffic by itself.'),
    intent('console-choice', 'single-choice', 'You need to deliberately disable a bench port during a test. Which access arrangement best preserves your ability to restore it?', ['Use only a session carried by the port you will disable.', 'Use console access independent of that Ethernet connection.', 'Use a second in-band session that still depends on the same Ethernet path.', 'Rely on the endpoint application connection instead of an independent management path.'], [1], 'Independent console access survives the deliberate link interruption and lets you restore the selected port. A session on that port may disconnect.'),
    intent('default-evidence', 'cli-interpretation', 'The shown interface excerpt has no speed or duplex lines. Which conclusion is justified?', ['The port is necessarily forced to 10 Mb/s half duplex.', 'The port cannot transmit because no speed is configured.', 'Default settings may be omitted; inspect operational state to learn the actual result.', 'Startup configuration must contain hidden manual overrides.'], [2], 'Running configuration can omit defaults. Its absence of an override is not an operational speed measurement.', output('interface GigabitEthernet1/0/7\n description Bench recorder')),
    intent('save-boundary', 'single-choice', 'A verified change works now, but you also intend it to survive a restart. What operation records the current configuration for startup?', ['end', 'show interfaces status', 'no description', 'copy running-config startup-config'], [3], 'Copying running to startup retains the intended configuration across restart. end leaves configuration mode; show commands inspect rather than save.'),
    intent('retired-spare', 'troubleshooting', 'An audit finds a disconnected spare with shutdown configured. The inventory says “retired; keep disabled.” What is the appropriate response?', ['Enable it because every down port is a fault.', 'Leave it disabled and confirm the documented intent.', 'Remove shutdown after a cable check even though the inventory says retired.', 'Reset it to defaults without preserving the intended disabled state.'], [1], 'The desired state matters. A deliberate disabled spare is not an outage merely because its operational state is down.'),

    agreement('shared-capability', 'single-choice', 'A working copper link has auto enabled on both ends. The switch offers 10/100/1000, while the endpoint offers 10/100; both offer full duplex. What mode can they normally agree on?', ['1000 Mb/s full duplex', '100 Mb/s full duplex', '1000 Mb/s half duplex', 'A different operating speed in each direction'], [1], 'The common capability is at most 100 Mb/s, with full duplex supported by both. The faster switch cannot add a missing endpoint capability.'),
    agreement('simultaneous-direction', 'classification', 'A point-to-point Ethernet link can send and receive simultaneously without the normal collision-detection procedure. Classify its duplex behavior.', ['Half duplex', 'Full duplex', 'Administrative shutdown'], [1], 'Full duplex provides simultaneous directions. Half duplex uses shared-medium access rules; shutdown is an administrative state.'),
    agreement('legacy-information', 'single-choice', 'On a legacy 100-Mb/s copper connection, the auto side detects the peer’s speed but receives no negotiation information about duplex. Why can the link perform poorly even when it is up?', ['Speed detection supplies a reliable full-duplex advertisement.', 'A connected state necessarily means both ends exchanged duplex advertisements.', 'The automatic side may use half duplex while the forced peer uses full.', 'Matching speed prevents any duplex difference from affecting traffic.'], [2], 'Legacy speed detection does not reveal the peer’s forced duplex. Half/full disagreement can leave the link up while harming traffic.'),
    agreement('coordinate-repair', 'configuration-selection', 'Both endpoints support normal autonegotiation. A legacy link has mismatched duplex settings. Which plan is appropriate?', ['Coordinate auto speed/duplex at both ends, then verify their operation and traffic.', 'Force a higher speed on the switch and leave the peer untouched.', 'Change only the port description.', 'Clear counters and assume the mismatch is repaired.'], [0], 'Restore compatible negotiated settings on both capable ends and prove the result. Clearing counters or relabeling cannot reconcile the operating modes.'),
    agreement('automatic-not-health', 'multiple-choice', 'A summary shows a-full and a-1000 on a connected interface. Which statements are supported? Select all that apply.', ['The local operating duplex is full.', 'The local operating speed is 1000 Mb/s.', 'Every received frame has been error-free.', 'The a-prefix indicates automatic selection of those values.'], [0,1,3], 'The fields report automatically selected local operating values. You still need counters and traffic evidence to assess health.'),
    agreement('media-boundary', 'true-false', 'The fallback behavior taught for a legacy 10/100 copper port can be applied unchanged to every fiber and multi-Gigabit interface.', ['True', 'False'], [1], 'Negotiation controls, supported modes and media requirements vary. Keep the legacy rule in scope and inspect the relevant port/module documentation.'),
    agreement('shared-hub', 'single-choice', 'A historical hub creates a shared Ethernet segment. Which duplex model belongs to that shared-medium design?', ['Full duplex, because each attached NIC has its own connector.', 'Half duplex with shared-medium collision handling.', 'Full duplex whenever at least one attached NIC supports Gigabit Ethernet.', 'An independent simultaneous path between every pair of hosts.'], [1], 'The hub shares the medium rather than creating independent switched full-duplex links. Half-duplex access/collision rules apply to that legacy design.'),
    agreement('different-speeds', 'troubleshooting', 'A lab’s 10/100-capable endpoints are deliberately forced to 10 Mb/s and 100 Mb/s on the same cable. What should you investigate first when no usable link forms?', ['A mismatch in physical operating speed.', 'The wording of the interface description.', 'The startup configuration before checking the active port settings.', 'A higher-layer addressing issue before establishing physical link compatibility.'], [0], 'The ends must use a compatible physical operating mode. Incompatible forced speeds are a direct link-formation problem, not a documentation problem.'),
    agreement('operating-vs-supported', 'single-choice', 'A port is described as 10/100/1000 capable. Which observation identifies what it is using on the current connection?', ['The maximum number in its marketing specification alone.', 'The peer’s maximum supported rate by itself.', 'The operational speed field for that interface.', 'A manually configured speed line without verifying whether the link is operating.'], [2], 'Capabilities describe available choices; operational output reports the selected current speed.'),

    evidence('pick-detailed-command', 'single-choice', 'A link remains connected while traffic is unreliable. You want detailed error counters for only Gi1/0/8. Which command best fits?', ['show interfaces description', 'show interfaces GigabitEthernet1/0/8', 'show running-config interface GigabitEthernet1/0/8', 'show startup-config'], [1], 'The detailed interfaces command exposes state and counters for that port. Description and configuration views answer different questions.'),
    evidence('intent-from-excerpt', 'cli-interpretation', 'The maintenance ticket authorizes this port to return to service. What should be checked before removing the restriction shown?', ['That the physical port and expected peer match the ticket.', 'That every spare interface is enabled first.', 'That the description is deleted before any observation.', 'That a speed command is added without checking the peer.'], [0], 'Verify the target identity and intended use before changing administrative permission.', output('interface GigabitEthernet1/0/8\n description Bench observer\n shutdown')),
    evidence('missing-link', 'multiple-choice', 'A port is enabled but reports notconnect. Which observations can narrow the physical-link investigation? Select all that apply.', ['Peer power and administrative state.', 'Cable and termination condition.', 'Mutually supported operating settings.', 'Changing only the host IP address to force the physical link up.'], [0,1,2], 'notconnect has multiple possible causes. Peer, physical path and operating settings are relevant; IP addressing does not establish the physical signal.'),
    evidence('protection-category', 'classification', 'A port reports err-disabled and a protection reason. Which category best describes the situation?', ['A normal enabled connection proven healthy.', 'A protection-triggered removal from service requiring cause investigation.', 'A label-only configuration change.'], [1], 'err-disabled is a protective state. It is not equivalent to an intentional shutdown or a healthy link; investigate the reported cause before recovery.'),
    evidence('link-vs-application', 'true-false', 'up/up on the local Ethernet interface proves that a remote application is reachable and that no packets are being damaged.', ['True', 'False'], [1], 'up/up reports local link-level operation. Application reachability and traffic integrity require additional evidence.'),
    evidence('configured-intent', 'single-choice', 'You need to know which explicit settings currently apply to one port, before editing them. Which view should you start with?', ['A count of all received packets.', 'The peer’s application log alone.', 'show running-config interface for the selected port.', 'The maximum speed supported by the chassis.'], [2], 'The selected running-configuration excerpt records current explicit intent. Counters and capabilities do not list the applied subcommands.'),
    evidence('peer-label-overview', 'single-choice', 'You are checking peer descriptions across several ports and want their line/protocol states in a concise inventory. Which command serves that purpose?', ['show interfaces description', 'copy running-config startup-config', 'configure terminal', 'no description'], [0], 'The description view combines configured peer labels with a concise status inventory. The other commands save, enter configuration or remove a label.'),
    evidence('range-verification', 'multiple-choice', 'A description was applied to a two-port range. What should a complete verification include? Select all that apply.', ['The current configuration of each intended member.', 'The expected peer identity for each member.', 'The assumption that one working member proves both are healthy.', 'The current state of each connection if operational readiness matters.'], [0,1,3], 'Range mode shares the edit, not the physical outcome. Check the intended per-port configuration, peer identity and operational state separately.'),
    evidence('independent-branch', 'topology-reasoning', 'The recorder port is deliberately shut down in this topology. Which result is consistent with an interface-scoped change?', ['Both physical links must go down because they share a switch.', 'The recorder link goes down while the observer link can remain connected.', 'Only the observer link goes down because forwarding is centralized.', 'The recorder link must stay up because its endpoint is powered.'], [1], 'Each physical interface has its own administrative state. Shutting the recorder’s port does not require the observer’s link to go down.', [{ kind: 'diagram', id: 'question-links', caption: 'Independent bench connections', description: 'A recorder and observer each have a separate cable to Bench-SW. Only the recorder interface is administratively disabled.', width: 480, height: 260, nodes: [{ id: 'sw', label: 'Bench-SW', kind: 'switch', x: 240, y: 55 }, { id: 'rec', label: 'Recorder · disabled port', kind: 'client', x: 100, y: 200 }, { id: 'obs', label: 'Observer · enabled port', kind: 'client', x: 380, y: 200 }], links: [{ from: 'sw', to: 'rec' }, { from: 'sw', to: 'obs' }] }]),

    diagnosis('crc-delta', 'cli-interpretation', 'How many new CRC errors occurred during this observation window?', ['2', '17', '19', '2,500'], [0], 'Subtract the initial cumulative count from the final count: 19 − 17 = 2 new CRC errors.', output('Window start: 10000 packets input, 17 CRC\nWindow end:   12500 packets input, 19 CRC')),
    diagnosis('late-collision-evidence', 'troubleshooting', 'A legacy half-duplex link develops new late collisions under load. Which follow-up is justified?', ['Assume all collision counters are harmless, including late collisions.', 'Compare both-end duplex settings and investigate the physical segment.', 'Force Gigabit operation without checking endpoint capability.', 'Change the peer label and declare the fault resolved.'], [1], 'Late collisions warrant investigation; duplex disagreement and an unsuitable physical segment are candidate causes. The counter does not uniquely prove one cause.'),
    diagnosis('traffic-category', 'classification', 'The packets output count rises during a successful traffic test, while relevant error counters stay fixed. Classify the rising count.', ['Evidence of transmitted traffic, not an error count by itself.', 'Definitive proof of a duplex mismatch.', 'An administrative shutdown indication.'], [0], 'Traffic counters count traffic. Their increase alone is not an error condition; compare actual error deltas and the expected test result.'),
    diagnosis('full-duplex-collisions', 'true-false', 'Normal collision detection is active on a point-to-point Ethernet link operating at full duplex.', ['True', 'False'], [1], 'Full-duplex links send and receive simultaneously without the normal half-duplex collision-detection process.'),
    diagnosis('retain-baseline', 'single-choice', 'Before testing a suspected cable fault, what should you do with the current error counters?', ['Clear them immediately so the fault disappears from the display.', 'Preserve the counts and observation conditions before changing or clearing evidence.', 'Copy running configuration to startup to save the counters.', 'Delete the interface description to reset its statistics.'], [1], 'Preserving the baseline lets you calculate deltas and evaluate the repair. Configuration saves and descriptions are not counter storage/reset operations.'),
    diagnosis('controlled-substitution', 'troubleshooting', 'CRCs stop increasing during comparable traffic after only the cable is replaced. What is the strongest defensible conclusion?', ['The entire network is permanently proven error-free.', 'The original physical connection is implicated; repeat the test and inspect it.', 'A duplex mismatch is proven even though both ends were unchanged.', 'Every old CRC was generated by the replacement cable.'], [1], 'The controlled change supports a physical-path hypothesis. It does not identify every component or guarantee future stability; retesting is necessary.'),
    diagnosis('repair-proof', 'multiple-choice', 'Which evidence supports a successful link repair? Select all that apply.', ['Expected traffic succeeds during the retest.', 'Relevant error counts do not newly increase under comparable traffic.', 'The link operates at the intended compatible mode.', 'The interface description alone looks more accurate.'], [0,1,2], 'Traffic, error deltas and operating mode together support the repair. A correct label is useful documentation but cannot prove traffic health.'),
    diagnosis('aggregate-counter', 'single-choice', 'Input errors and the displayed receive subcounters do not sum exactly on a particular platform. Which interpretation is appropriate?', ['The total always counts distinct damaged frames regardless of platform accounting.', 'Any difference proves that the CRC subcounter itself is invalid.', 'Some classifications/accounting can overlap; check the platform definitions and deltas.', 'Every counter must be cleared before any diagnosis is possible.'], [2], 'Input-error accounting can include overlapping or differently reported categories. Use platform definitions and recent changes rather than assuming a universal arithmetic equality.'),
    diagnosis('fault-boundary', 'topology-reasoning', 'On the bench, only the observer’s receive CRCs grow. The recorder connection remains healthy. Which investigation stays closest to the evidence?', ['Reset both interfaces and discard their baseline counters.', 'Start with the observer link, its peer and physical path, keeping the recorder as a reference.', 'Ignore the affected link and start with the unchanged recorder connection.', 'Enable every disabled spare to increase available paths.'], [1], 'The localized symptom supports starting with the affected link and preserving the healthy reference. Wider resets discard information and change unrelated state.'),
  ].map(q => ({ ...q, distractorExplanations: distractorGuidance[q.id] })),
};
