import type { Chapter, Command, ConfigChecklist, DiagramBlock, KeyTopic, ReadingBlock } from '../../learning/model';
const prose = (...paragraphs: string[]): ReadingBlock => ({ kind: 'prose', paragraphs });
const cli = (id: string, caption: string, commands: string[], output?: string): ReadingBlock => ({ kind: 'cli', id, caption, lines: [...commands.map(commandId => ({ kind: 'command' as const, commandId })), ...(output ? [{ kind: 'output' as const, text: output }] : [])] });
export const portCommands: readonly Command[] = [
  { copyable: true, id: 'ports-status', text: 'show interfaces status', prompt: 'Bench-SW#' },
  { copyable: true, id: 'port-seven-detail', text: 'show interfaces GigabitEthernet1/0/7', prompt: 'Bench-SW#' },
  { copyable: true, id: 'port-eight-detail', text: 'show interfaces GigabitEthernet1/0/8', prompt: 'Bench-SW#' },
  { copyable: true, id: 'port-seven-config', text: 'show running-config interface GigabitEthernet1/0/7', prompt: 'Bench-SW#' },
  { copyable: true, id: 'port-eight-config', text: 'show running-config interface GigabitEthernet1/0/8', prompt: 'Bench-SW#' },
  { copyable: true, id: 'ports-description', text: 'show interfaces description', prompt: 'Bench-SW#' },
  { copyable: true, id: 'ports-protection', text: 'show interfaces status err-disabled', prompt: 'Bench-SW#' },
  { copyable: true, id: 'port-logs', text: 'show logging', prompt: 'Bench-SW#' },
  { copyable: true, id: 'ports-configure', text: 'configure terminal', prompt: 'Bench-SW#' },
  { copyable: true, id: 'select-seven', text: 'interface GigabitEthernet1/0/7', prompt: 'Bench-SW(config)#' },
  { copyable: true, id: 'select-eight', text: 'interface GigabitEthernet1/0/8', prompt: 'Bench-SW(config)#' },
  { copyable: true, id: 'select-nine', text: 'interface GigabitEthernet1/0/9', prompt: 'Bench-SW(config)#' },
  { copyable: true, id: 'label-seven', text: 'description Bench recorder', prompt: 'Bench-SW(config-if)#' },
  { copyable: true, id: 'label-eight', text: 'description Bench observer', prompt: 'Bench-SW(config-if)#' },
  { copyable: true, id: 'label-nine', text: 'description Retired bench spare', prompt: 'Bench-SW(config-if)#' },
  { copyable: true, id: 'port-stop', text: 'shutdown', prompt: 'Bench-SW(config-if)#', highlight: true },
  { copyable: true, id: 'port-allow', text: 'no shutdown', prompt: 'Bench-SW(config-if)#', highlight: true },
  { copyable: true, id: 'port-speed-auto', text: 'speed auto', prompt: 'Bench-SW(config-if)#' },
  { copyable: true, id: 'port-duplex-auto', text: 'duplex auto', prompt: 'Bench-SW(config-if)#' },
  { copyable: true, id: 'port-unlabel', text: 'no description', prompt: 'Bench-SW(config-if)#' },
  { copyable: true, id: 'port-speed-default', text: 'no speed', prompt: 'Bench-SW(config-if)#' },
  { copyable: true, id: 'port-duplex-default', text: 'no duplex', prompt: 'Bench-SW(config-if)#' },
  { copyable: true, id: 'ports-end', text: 'end', prompt: 'Bench-SW(config-if)#' },
  { copyable: true, id: 'ports-save', text: 'copy running-config startup-config', prompt: 'Bench-SW#' },
  { copyable: true, id: 'select-spares', text: 'interface range GigabitEthernet1/0/11 - 12', prompt: 'Bench-SW(config)#' },
  { copyable: true, id: 'label-spares', text: 'description Unassigned bench sockets', prompt: 'Bench-SW(config-if-range)#' },
  { copyable: true, id: 'range-end', text: 'end', prompt: 'Bench-SW(config-if-range)#' },
];
export const portTopics: readonly KeyTopic[] = [
  { id: 'port-intent-and-evidence', title: 'Separate intent from evidence', summary: 'Configuration says what is allowed; operational state and measurements say what actually happens.', paragraphs: ['An enabled port can still have no signal. A connected port can still lose damaged frames. Read configuration, link state and recent traffic health as separate pieces of evidence.'] },
  { id: 'port-both-ends', title: 'Treat a link as a pair', summary: 'Compare capabilities and operating settings at both ends before changing speed or duplex.', paragraphs: ['Autonegotiation lets compatible endpoints agree on a shared operating mode. Forcing one end of a legacy link while leaving the other automatic can remove the information needed for a matching duplex choice.'] },
  { id: 'port-permission-not-proof', title: 'Enabling is permission, not proof', summary: 'no shutdown permits an interface to operate; it does not supply a cable, peer or healthy signal.', paragraphs: ['After an administrative change, verify the selected interface and the peer. Use the resulting status to choose the next observation rather than repeating the same configuration blindly.'] },
  { id: 'port-measure-change', title: 'Measure the change', summary: 'Counter deltas during comparable traffic reveal current faults better than an old cumulative total.', paragraphs: ['Record a baseline, make one justified change and repeat the traffic test. Old errors remain in cumulative counters; new increases are the useful evidence that a problem continues.'] },
];
export const portChecklist: ConfigChecklist = {
  id: 'verify-ethernet-port-change', title: 'Verify an Ethernet port change', category: 'ethernet-ports', order: 1,
  purpose: 'A short field reference for changing one intended lab port and proving the result. Adapt the interface identifier to your device; preserve peer access and existing policy.',
  steps: [
    { id: 'baseline', instruction: 'Identify the port and preserve its current settings and state before editing.', commandIds: ['ports-status', 'port-seven-config', 'port-seven-detail'], verification: 'The physical label, interface identifier and expected peer agree.' },
    { id: 'intent', instruction: 'Enter only the intended interface. Add a useful peer label and retain negotiated defaults when both ends support them.', commandIds: ['ports-configure', 'select-seven', 'label-seven', 'port-speed-auto', 'port-duplex-auto'], verification: 'The prompt is interface configuration mode for the selected port; the peer is also configured to negotiate.' },
    { id: 'permit', instruction: 'Enable the planned connection, then leave configuration mode.', commandIds: ['port-allow', 'ports-end'], verification: 'No shutdown allows operation. A live peer and a suitable cable are still required.' },
    { id: 'observe', instruction: 'Check operational state and the actual speed/duplex, then compare both ends.', commandIds: ['ports-status', 'port-seven-detail'], verification: 'The intended port is connected/up-up at a mutually supported mode; investigate protective or disconnected states before proceeding.' },
    { id: 'measure', instruction: 'Run a comparable traffic test and re-read the detailed counters. Keep the successful result, then save only if the change should survive a restart.', commandIds: ['port-seven-detail', 'ports-save'], verification: 'Expected traffic succeeds and relevant error counters do not continue to grow. Do not save an unverified experiment.' },
  ],
  verification: ['Check the selected interface, its peer and an untouched reference port.', 'Separate connectivity success from error-free operation; record the observation interval and traffic used.'],
  commonMistakes: ['Editing a similarly numbered port without checking the physical label.', 'Treating connected or a-full as proof that applications and cabling are healthy.', 'Forcing only one end of a legacy link.', 'Clearing counters before recording the fault, or blaming old errors after a successful repair.'],
  relatedChapterIds: ['ethernet-port-operations'],
};
export const benchDiagram: DiagramBlock = {
  kind: 'diagram', id: 'bench-links', caption: 'Two independent connections on an isolated bench',
  description: 'Bench-SW connects the recorder through Gi1/0/7 and the observer through Gi1/0/8. The observer is a reference connection while the recorder port is tested. Both hosts are in the same existing lab VLAN.',
  width: 600, height: 300,
  nodes: [{ id: 'bench-switch', label: 'Bench-SW', kind: 'switch', x: 300, y: 60 }, { id: 'recorder', label: 'Recorder · 192.0.2.41/24', kind: 'client', x: 135, y: 225 }, { id: 'observer', label: 'Observer · 192.0.2.42/24', kind: 'client', x: 465, y: 225 }],
  links: [{ from: 'bench-switch', to: 'recorder', label: 'Gi1/0/7' }, { from: 'bench-switch', to: 'observer', label: 'Gi1/0/8' }],
};
export const portChapter: Chapter = {
  id: 'ethernet-port-operations', slug: 'ethernet-port-operations', subjectId: 'ccna', partId: 'ccna-ethernet-operations', publication: 'published',
  title: 'Ethernet Ports: Configure, Verify, Diagnose',
  intro: 'A link light is a starting point. Learn to connect the intended port, read what the switch is actually doing, and distinguish a disconnected link from one that is connected but unhealthy.',
  objectives: [
    { id: 'interface-intent', text: 'Choose an interface or range and apply or reverse an intentional configuration change.' },
    { id: 'link-agreement', text: 'Explain negotiated speed and duplex, and avoid incompatible endpoint settings.' },
    { id: 'interface-evidence', text: 'Interpret interface state and choose the right verification evidence.' },
    { id: 'link-diagnosis', text: 'Diagnose degraded links using both-end checks, counter deltas and a controlled retest.' },
  ],
  sections: [
    { id: 'quick-understanding', title: 'Quick understanding: three questions for every port', blocks: [
      prose('Start with intent: should this connection be enabled, and which peer belongs here? Then inspect operation: has a physical link formed, and at what speed and duplex? Finally measure health: does useful traffic pass without new errors?', 'These questions explain why “no shutdown” and “connected” are useful but incomplete answers. A command changes intent; the switch still needs a working cable and peer. A working link can still corrupt or lose traffic.'),
      { kind: 'key-topic', topicId: 'port-intent-and-evidence' },
      { kind: 'note', label: 'Before you practice', paragraphs: ['Use an isolated lab with console access and spare Ethernet ports. You should recognize privileged EXEC, global configuration and interface configuration prompts. The labs assume two powered hosts already share one lab VLAN and have the shown addresses. No routing or switch-management address is required.', 'Commands use Catalyst-style IOS/IOS XE syntax. Port identifiers, supported settings and output fields vary by hardware and release. All output excerpts here are independently authored illustrations, not measurements from your device.'] },
    ] },
    { id: 'read-the-port', title: 'Study: build an evidence trail', blocks: [
      prose('Use show interfaces status to scan many ports quickly. Choose the intended interface, then inspect show running-config interface for configured intent and show interfaces for detailed state and counters. show interfaces description is useful when you need a concise peer-label inventory.', 'A summary can tell you that a port is not connected. It cannot identify the failed cable, a powered-off endpoint or incompatible settings on its own. Use the next observation to narrow the possibilities.'),
      cli('first-port-scan', 'Find the port before changing it', ['ports-status', 'port-seven-config'], 'Port      Name             Status       Vlan  Duplex  Speed   Type\nGi1/0/7   Bench recorder   disabled     1     auto    auto    10/100/1000BaseTX\nGi1/0/8   Bench observer   connected    1     a-full  a-1000  10/100/1000BaseTX\n\ninterface GigabitEthernet1/0/7\n description Bench recorder\n shutdown'),
      { kind: 'table', id: 'port-evidence-guide', caption: 'Choose the next observation from the evidence you have', mode: 'cards', columns: [{ id: 'signal', label: 'Signal' }, { id: 'meaning', label: 'What it supports' }, { id: 'next', label: 'Next observation' }], rows: [
        { id: 'disabled', cells: ['disabled / administratively down', 'An administrative setting prevents operation.', 'Check the intended port and its running configuration before enabling it.'] },
        { id: 'notconnect', cells: ['notconnect / down-down', 'A usable link has not formed; the cause is not identified.', 'Inspect peer power/state, cable and mutually supported settings.'] },
        { id: 'protected', cells: ['err-disabled', 'A protection mechanism has taken the port out of service.', 'Read the reported reason and logs. Correct the cause before recovery.'] },
        { id: 'connected', cells: ['connected / up-up', 'The interface is operational at the link level.', 'Check both-end settings, traffic and recent error deltas; this does not prove end-to-end reachability.'] },
      ] },
      prose('An err-disabled port is different from a port you deliberately shut down. Recovery without fixing its cause can repeat the fault. show interfaces status err-disabled and show logging help gather evidence; recovery policy and commands depend on the actual protection feature.', 'Do not infer “default” from silence without checking the platform. Running configuration commonly omits default settings. A missing speed or duplex line can therefore be consistent with automatic operation; operational output tells you the result.'),
      { kind: 'key-topic', topicId: 'port-permission-not-proof' },
    ] },
    { id: 'agree-on-a-link', title: 'Study: the two ends must agree', blocks: [
      prose('A multi-speed port supports several modes but uses one operating mode for a particular link. When both ends negotiate normally, they select a mutually supported speed and duplex. A 10/100 endpoint cannot gain Gigabit capability just because the switch supports it.', 'Full duplex allows simultaneous transmission and reception. Half duplex takes turns on the shared medium and uses collision handling. Historical hub segments require half-duplex behavior; a modern point-to-point full-duplex connection has no normal collision-detection process.', 'On legacy 10/100 copper, an automatic endpoint may detect a forced peer’s speed without learning its duplex setting. It can fall back to half duplex while the peer is forced full. The link may stay up yet perform badly. Compare the actual settings at both ends, not just one configuration.'),
      { kind: 'key-topic', topicId: 'port-both-ends' },
      { kind: 'note', label: 'Keep the media and platform in the rule', paragraphs: ['Prefer auto on both capable endpoints. If a documented peer limitation requires fixed settings, coordinate both ends and verify the resulting operation. Do not apply legacy 10/100 fallback predictions to copper Gigabit, multi-Gigabit or fiber ports.', 'A configured speed does not universally mean every negotiation function is disabled. Supported duplex modes and negotiation controls depend on the port/module. Check its configuration guide rather than assuming that every interface behaves like an old Fast Ethernet port.'] },
      cli('negotiated-port-view', 'Read the operating mode, then verify its health', ['port-eight-detail'], 'GigabitEthernet1/0/8 is up, line protocol is up (connected)\n  Full-duplex, 1000Mb/s\n  7320 packets input\n  0 input errors, 0 CRC\n  6891 packets output, 0 output errors\n  0 collisions, 0 late collision'),
      prose('In Catalyst status summaries, a-full and a-1000 indicate automatically selected operating values. They are not health certificates and do not prove the peer’s whole configuration. Compare both endpoints when a legacy mismatch is suspected; detailed output and counter changes supply additional evidence.'),
    ] },
    { id: 'make-a-port-change', title: 'Practice: change intent in the right context', blocks: [
      prose('At the privileged EXEC prompt, configure terminal enters global configuration. interface selects one port; commands that follow apply there until you leave that context. A description documents intent without changing forwarding or negotiation. shutdown deliberately prevents operation; no shutdown removes that restriction.', 'The following sequence prepares only Gi1/0/7. The separate verification step matters as much as the edit: an accepted command is not proof of a healthy connection.'),
      cli('port-change-sequence', 'Prepare the recorder connection', ['ports-configure', 'select-seven', 'label-seven', 'port-speed-auto', 'port-duplex-auto', 'port-allow', 'ports-end']),
      prose('For a group of genuinely identical changes, interface range applies subsequent commands to every selected port. The running configuration stores settings under the individual interfaces. Check each member afterward; a range selection does not guarantee that every port has the same cable or peer.'),
      cli('port-range-example', 'Label two unused bench sockets without enabling them', ['ports-configure', 'select-spares', 'label-spares', 'range-end']),
      prose('Use no description to remove a label. On applicable Catalyst interfaces, no speed and no duplex remove explicit overrides and return those settings to their defaults. These commands do not erase all interface configuration. Do not reset a whole interface just to undo one experiment.', 'Running configuration is the current configuration; startup configuration is what the device uses at startup. Save a verified intentional change with copy running-config startup-config. Leaving configuration mode with end does not perform that save.'),
      { kind: 'walkthrough', id: 'port-change-walkthrough', title: 'A small before-and-after walkthrough', steps: [
        { id: 'identify', title: 'Confirm the target', content: [prose('The physical socket labeled recorder is Gi1/0/7. Its summary says disabled, and its configuration includes shutdown. The observer remains connected on Gi1/0/8. This evidence supports an administrative correction on one port, not a switch-wide reset.')] },
        { id: 'change', title: 'Apply the intended state', content: [prose('Select Gi1/0/7 and remove its shutdown restriction. Keep automatic settings on both capable ends. Leave the observer configuration alone.')] },
        { id: 'prove', title: 'Prove the outcome', content: [cli('walkthrough-verify', 'Check the corrected connection', ['ports-status', 'port-seven-detail']), prose('Expect connected and up/up with a mutually supported speed/duplex when the peer and cable are working. Then pass traffic and compare counters. If the result is notconnect, the administrative edit succeeded but another link condition still needs attention.')] },
      ] },
      { kind: 'checklist', checklistId: 'verify-ethernet-port-change' },
    ] },
    { id: 'measure-link-health', title: 'Study: measure health while the link is up', blocks: [
      prose('CRC errors mean received frames failed the frame-check calculation. They suggest corruption but do not uniquely identify a damaged cable: peer hardware and duplex problems can also be involved. Start with both-end settings and the physical path, then substitute one known-good component when justified.', 'Collisions can occur on historical half-duplex segments. Late collisions deserve investigation, including duplex disagreement or an out-of-spec physical segment. Full-duplex operation does not use normal collision detection. A lone counter name is a clue, not a complete diagnosis.', 'Runts and giants describe frame-size anomalies; frame/align errors concern malformed framing. Their exact accounting can depend on platform, release, tagging and jumbo-frame configuration. Input errors aggregate several receive problems; overlapping classifications mean you should not demand that every displayed subcounter sum exactly to that total.'),
      { kind: 'key-topic', topicId: 'port-measure-change' },
      { kind: 'table', id: 'measurement-windows', caption: 'Authored measurement windows: compare new errors under similar traffic', mode: 'cards', columns: [{ id: 'window', label: 'Window' }, { id: 'frames', label: 'New received frames' }, { id: 'crc', label: 'New CRC errors' }, { id: 'reading', label: 'Interpretation' }], rows: [
        { id: 'before', cells: ['Before substitution', '4,000', '32', 'Errors are increasing while traffic is being received.'] },
        { id: 'after', cells: ['After substitution', '4,100', '0', 'No new CRCs in this test window; repeat enough traffic to confirm stability.'] },
      ] },
      prose('Record timestamps, packet counts and relevant errors before changing anything. Keep the traffic and interval comparable, then compute the differences. A large total left over from yesterday does not prove a current fault. Increasing packets input/output is usually evidence of traffic, not an error condition by itself.'),
    ] },
    { id: 'guided-port-lab', title: 'Guided Lab: isolate and restore one bench connection', blocks: [
      { kind: 'guided-lab', id: 'bench-maintenance-lab', title: 'Keep a reference connection while you test', goal: 'Deliberately isolate the recorder, prove the scope of the change, then restore and measure its connection.', prerequisites: ['An isolated Catalyst-style lab switch with console access; adapt Gi1/0/7 and Gi1/0/8 to your available ports.', 'Recorder 192.0.2.41/24 and observer 192.0.2.42/24 are powered, use auto speed/duplex, and share the same existing lab VLAN. Permit the test ICMP traffic on the lab hosts.', 'Use suitable cables and precheck that both links and host-to-host traffic work.'], startingState: [benchDiagram, prose('Both connections begin enabled and working. Save a copy of the original interface configuration locally before the exercise. Do not use a port that carries your management connection.')], steps: [
        { id: 'baseline', title: 'Record the healthy baseline', action: [cli('lab-baseline', 'Inspect both ports', ['ports-status', 'port-seven-config', 'port-seven-detail', 'port-eight-detail'])], why: 'You need evidence from the target and the untouched port to distinguish a local edit from a wider failure.', verify: [prose('Confirm both ports are connected, note their speed/duplex and current counters, and test ping from the recorder to 192.0.2.42 using its operating system.')], expectedResult: 'Both links are up/up, the intended peer labels match, and the permitted host-to-host test succeeds.' },
        { id: 'isolate', title: 'Disable the recorder connection only', action: [cli('lab-isolate', 'A deliberate administrative change', ['ports-configure', 'select-seven', 'port-stop', 'ports-end'])], why: 'This controlled fault establishes what an administrative state change looks like without disturbing the reference port.', verify: [cli('lab-isolation-proof', 'Check scope rather than guessing from a failed ping', ['ports-status', 'port-seven-detail'], 'GigabitEthernet1/0/7 is administratively down, line protocol is down (disabled)'), prose('Check Gi1/0/8 separately. The observer link should remain connected even though the recorder can no longer exchange traffic.')], expectedResult: 'The recorder port is disabled; the observer link stays up. The recorder’s host-to-host ping fails because its local link is intentionally unavailable.' },
        { id: 'restore', title: 'Restore and label the intended connection', action: [cli('lab-restore', 'Restore permission to operate', ['ports-configure', 'select-seven', 'label-seven', 'port-speed-auto', 'port-duplex-auto', 'port-allow', 'ports-end'])], why: 'The label documents the peer, and coordinated auto settings let capable endpoints establish a compatible operating mode.', verify: [cli('lab-restoration-proof', 'Observe the result after link convergence', ['ports-status', 'port-seven-detail'])], expectedResult: 'After the link and existing lab forwarding state settle, the recorder is connected/up-up with a common supported speed and duplex.' },
        { id: 'retest', title: 'Repeat traffic and compare the measurements', action: [prose('Repeat the same permitted ping test and a comparable period of lab traffic. Read both interfaces again and calculate new error counts. Keep your before/after notes.')], why: 'Restored state alone cannot establish that the physical connection is healthy.', verify: [cli('lab-traffic-proof', 'Read the new counters', ['port-seven-detail', 'port-eight-detail'])], expectedResult: 'Traffic succeeds; relevant receive/error counters do not newly increase during the test. The observer’s configuration remains unchanged. Restore the original recorder description if it was only an exercise; save only the final configuration you intend to retain.' },
      ] },
    ] },
    { id: 'challenge-port-lab', title: 'Challenge Lab: recover a bench without enabling its spare', blocks: [
      { kind: 'challenge-lab', id: 'bench-audit-challenge', title: 'Decide what should change', goal: 'Restore an intended connection while preserving an intentionally retired port.', startingState: [prose('On the same isolated bench, the recorder’s Gi1/0/7 is healthy. The observer’s Gi1/0/8 was left shut down after maintenance. Gi1/0/9 is a disconnected retired spare and must stay administratively disabled. Both host NICs use auto. You have console access.')], requirements: ['Identify the failed intended connection from state and configuration, not a guessed range.', 'Restore only the observer, add its accurate peer description, and verify both active links.', 'Keep the retired spare disabled and avoid altering Gi1/0/7.', 'Demonstrate host traffic and a comparable counter retest before deciding whether to save.'], expectedEndState: 'Gi1/0/7 and Gi1/0/8 are connected and healthy; Gi1/0/9 remains disabled. Your evidence shows exactly which interface changed.', hints: ['One range command may be convenient, but the three ports do not share the same intended state.'], solution: [prose('Collect each port’s state and configuration. Select Gi1/0/8 alone: this is the connection the requirements authorize you to restore.'), cli('challenge-solution-change', 'An interface-scoped repair', ['port-eight-config', 'ports-configure', 'select-eight', 'label-eight', 'port-speed-auto', 'port-duplex-auto', 'port-allow', 'ports-end']), cli('challenge-solution-evidence', 'Prove the active and retired states', ['ports-status', 'port-eight-detail']), prose('Test permitted host-to-host traffic and new error deltas. Check that Gi1/0/7 did not change and Gi1/0/9 is still disabled. Enabling a range containing the spare would violate the intended end state even if the ping started working. Save only after the complete result is verified.')] },
    ] },
    { id: 'troubleshoot-port', title: 'Troubleshooting Practice: connected, but unreliable', blocks: [
      { kind: 'troubleshooting', id: 'bench-corruption-case', title: 'Use a controlled substitution to test your hypothesis', scenario: 'The bench observer intermittently loses recorded traffic. Both ends report full duplex at the expected speed; the switch still says connected. You have two equally long traffic measurements around a cable substitution.', symptoms: ['The link stays up while receive errors grow.', 'The replacement test uses the same endpoints, settings and comparable traffic.', 'No new late collisions are observed in either window.'], evidence: [
        { kind: 'cli', id: 'fault-window-evidence', caption: 'Authored excerpts from two diagnostic windows', lines: [{ kind: 'output', text: 'Before replacement, Gi1/0/8: up/up, full duplex, 1000Mb/s\nWindow start: 18000 packets input, 70 CRC, 0 late collision\nWindow end:   22000 packets input, 102 CRC, 0 late collision\n\nAfter replacement, same operating mode:\nWindow start: 22000 packets input, 102 CRC, 0 late collision\nWindow end:   26100 packets input, 102 CRC, 0 late collision' }] },
      ], learnerPrompt: 'What does the evidence support, what does it leave unproven, and what should you verify next?', diagnosis: 'The first window contains 32 new CRC errors. The comparable replacement window contains none. This supports a fault associated with the original physical connection, not a proven duplex mismatch.', explanation: [prose('A CRC increase reports damaged received frames; it does not identify a component by itself. With endpoint settings unchanged and the cable as the controlled variable, the improved result supports replacing or testing that physical path. The old total of 102 remains and is not a new error count.', 'One clean window does not prove that intermittent corruption will never return. A connector movement may also have affected the result. Retest under representative load and inspect the original cable/termination; investigate the peer or port if errors recur.')], correctiveAction: [prose('Keep the suitable known-good lab cable in place, inspect the removed cable and connectors, and record the change. Do not clear the original evidence or force an arbitrary duplex setting to make the counters look different.')], verification: [cli('fault-retest', 'Confirm ongoing stability', ['port-eight-detail']), prose('Repeat comparable traffic and confirm no new CRC/error growth, the expected operating mode and successful host traffic. Escalate the physical/peer investigation if the fault returns.')] },
    ] },
  ],
  summary: { paragraphs: ['Work from intent to evidence to measurement. Select the right interface, make a justified change, and verify both the peer and the operational result. Connected is a link state, not a promise of clean traffic.', 'Prefer negotiated settings on compatible ends, keep legacy/media-specific rules in their proper scope, and use counter deltas to test a diagnosis. The same evidence-driven procedure applies when the next fault looks different.'] },
};
